from random_dungeon_name import gen_random_dungeon_name

#Prints the HTML page for the client

def createResponse(debug, name, attributes, encounters,img_name):
    #Create the HTML file
    file_path = "saved_dungeons/"+img_name+".html"
    if name is None:
        name = gen_random_dungeon_name()
    file = open(file_path,"w")
    file.write("<html>\n")
    file.write("<meta charset=\"utf-8\">\n")
    file.write("<head> <title>" + name + "</title> \n")
    file.write("<link rel=\"shortcut icon\" href=\"../graphics/icon.ico\" type=\"image/vnd.microsoft.icon\" />\n")
    file.write("<script type=\"text/javascript\">\n")
    file.write("function hoverPdf(element){element.setAttribute(\"src\", \"../graphics/submit_pdf_hover.png\")}\n")
    file.write("function unhoverPdf(element){element.setAttribute(\"src\", \"../graphics/submit_pdf.png\")}\n")
    file.write("function hoverImg(element){element.setAttribute(\"src\", \"../graphics/submit_image_hover.png\")}\n")
    file.write("function unhoverImg(element){element.setAttribute(\"src\", \"../graphics/submit_image.png\")}\n")
    file.write("</script>\n")
    file.write("<style>\n")
    file.write("body{background-image: url(../graphics/bg.jpg); background-attachment: fixed; background-repeat: no-repeat; background-position: top center;font-family: 'Lora',serif;}\n")
    file.write(".content {width:90%;margin : auto;text-align: center;background-color: rgba(205,179,128,0.5);line-height: 2;font-size: 20px;}\n")
    file.write(".gitlink {margin: auto;text-align: center;}\n")
    file.write("input{font-size: 18px;}\n")
    file.write("select{font-size: 18px;}\n")
    file.write(".center {display: block;margin: auto}\n")
    file.write("div.dungeon img{height: 85%;}\n")
    file.write(".container {display: flex;justify-content: center;flex-wrap: wrap;width: 100%;margin: auto;text-align: center;}\n")
    file.write(".item{width: 280px;background-color: rgba(205,179,128,0.65);padding: 10px;border: 2px solid black;margin: 0;float:center}\n")
    file.write("div.logo img{width: 500px;}\n")
    file.write("@media only screen and (max-device-width: 1024px){.content{width: 100%;}div.dungeon img{width: 95%;height: auto;}}\n")
    file.write("@media print{\n")
    file.write("body{background-image: none;}\n")
    file.write(".breaks{display: none !important;}\n")
    file.write(".buttons{display: none !important;}\n")
    file.write(".content{width:100%;background-color: rgba(255,255,255,1);}\n")
    file.write("div.logo img{width: 300px;}\n")
    file.write("div.dungeon img{width: 700px;height: 700px;}\n")
    file.write(".item{background-color: rgba(255,255,255,1)}\n")
    file.write(".gitlink{display: none;}}\n")
    file.write("</style>\n")
    file.write("</head>\n")
    file.write("<body>\n")
    file.write("<div class=\"breaks\"><br><br><br><br><br><br></div>")
    file.write("<div class=\"content\">\n")
    file.write("<div class=\"logo\"><img class=\"center\" src=\"../graphics/DungeonGen.png\" alt=\"Dungeon Logo\"></div>\n")
    file.write("<h1>" + name + "</h1>\n")
    if debug:
        file.write("<h2>Values:</h2>\n")
        file.write(attributes)
    file.write("<div class=\"dungeon\"><br><img src=\"../saved_dungeons/"+img_name+".png\" alt=\"Dungeon Map\"><br></div>\n")
    file.write("<br><div class=\"buttons\">")
    file.write("<a onclick=\"window.print()\"><img src=\"../graphics/submit_pdf.png\" onmouseover=\"hoverPdf(this);\" onmouseout=\"unhoverPdf(this);\" alt=\"Download PDF\" style=\"width:300px\"></a> &nbsp;&nbsp;\n")
    file.write("<a href=\"../saved_dungeons/"+img_name+".png\" download=\"Dungeon\"><img src=\"../graphics/submit_image.png\" onmouseover=\"hoverImg(this);\" onmouseout=\"unhoverImg(this);\" alt=\"Download Image\" style=\"width:300px\"></a><br>\n")
    file.write("</div>\n")
    file.write(encounters)
    file.write("</div>\n")
    file.write("<div class=\"gitlink\"><br><a href=\"https://github.com/urschni/dndgen\"><img src=\"../graphics/GithubLogo.png\" alt=\"Github Link\" style=\"width:150px\"></a></div>\n")
    file.write("</body>\n")
    file.write("</html>")
    
    file.close()
       
    
    #Create Redirect
    print("Content-Type: text/html; charset=utf-8\n")
    print("<html>")
    print("<head>")
    print("<script type=\"text/javascript\">")
    print("window.location.href = \"../saved_dungeons/"+img_name+".html\"")
    print("</script>")
    print("<title>Page Redirection</title>")
    print("</head>")
    print("<body>")
    print("If you are not redirected automatically, follow this <a href=\"../saved_dungeons/"+img_name+".html\">link to example</a>.")
    print("</body>")
    print("</html>")